# Deployment manifest for the backend application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: malikzohaib1482/backend:latest10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
