apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-storage
  labels:
    app: mysql
    tier: database
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast-ssd
  hostPath:
    path: /mnt/data/mysql-storage
    type: DirectoryOrCreate
