# PersistentVolumeClaim manifest requesting storage from a PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-data
  labels:
    app: pv-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
  volumeName: pv-data
